Vagrant.configure("2") do |config|
  # use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "latex-test" do |cf1|
    cf1.vm.box = "ubuntu/bionic64"
    cf1.vm.hostname ="latex-test"
    cf1.vm.network :private_network, ip: "192.168.1.10"
    cf1.vm.provider "virtualbox" do |vb|
    	vb.memory = "2000"
    end
  end
  
end